# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  DataStructures_Project_config = debug

else ifeq ($(config),release)
  DataStructures_Project_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := DataStructures_Project

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

DataStructures_Project:
ifneq (,$(DataStructures_Project_config))
	@echo "==== Building DataStructures_Project ($(DataStructures_Project_config)) ===="
	@${MAKE} --no-print-directory -C build -f Makefile config=$(DataStructures_Project_config)
endif

clean:
	@${MAKE} --no-print-directory -C build -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   DataStructures_Project"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"